namespace BA;

permissionset 50100 GeneratedPermission
{
    Assignable = true;
    Permissions = tabledata "Child Customer_SG"=RIMD,
        tabledata "Invoice SG"=RIMD,
        tabledata "Invoice SG(Archived)"=RIMD,
        table "Child Customer_SG"=X,
        table "Invoice SG"=X,
        table "Invoice SG(Archived)"=X,
        report "Devices Sales Invoice"=X,
        report "Devices Sales Order"=X,
        report "Devices Sales Quote"=X,
        report "Pricing Sheet Sales Invoice"=X,
        report "Pricing Sheet Sales Order"=X,
        report "Pricing Sheet Sales Quote"=X,
        report "Project Posted Sales Invoice"=X,
        report "Project Sales Invoice"=X,
        report "Project Sales Order"=X,
        report "Project Sales Quote"=X,
        report "Sales Invoice_SG"=X,
        report "Sales Order_SG"=X,
        report "Sales Quote_SG"=X,
        report "Standard Sales - Invoices_SG"=X,
        report "Standard Sales - Invoice_SG"=X,
        report "Standard Sales Invoice T&M"=X,
        report "Standard Sales Order T&M"=X,
        report "Standard Sales Quote T&M"=X,
        codeunit "Data Management"=X,
        codeunit "Dimension Handler"=X,
        codeunit GenralSubscriber=X,
        codeunit SalesInvoiceCreation_SG=X,
        page "Child Customers_SG"=X,
        page "Create Invoice_SG"=X,
        page SalesInvoiceCuePage=X,
        page "Sherweb Invoices"=X,
        page Sherweb_Invoices=X,
        page "Sherweb_Invoices(Archived)"=X;
}